font_family JetBrainsMono Nerd Font Mono
font_size 13
disable_ligatures no
enable_audio_bell no
shell                zsh
shell_integration disable
cursor_shape block
url_style  curly
remember_window_size  no
window_padding_width  27
cursor_blink_interval 0
background_opacity            0.80
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0
sync_to_monitor no
# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
cursor #ece1d4
