#!/bin/bash
# ╔══════════════════════════════════════════════════════════╗
# ║         hyprdots — uninstaller                          ║
# ║  Restores your original setup or drops minimal config   ║
# ╚══════════════════════════════════════════════════════════╝

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/lib.sh"

BACKUP_DIR="$HOME/.config/hyprdots-backup"
MANIFEST="$BACKUP_DIR/manifest.txt"

ALL_PACKAGES=(
    "hyprland|Hyprland window manager"
    "hyprlock|Lock screen"
    "hypridle|Idle daemon"
    "hyprshot|Screenshot tool"
    "hyprsession|Session manager"
    "waybar|Status bar"
    "rofi-wayland|App launcher"
    "swaync|Notification center"
    "ghostty|Terminal emulator"
    "kitty|Terminal emulator"
    "swww|Wallpaper daemon"
    "wlogout|Logout menu"
    "wl-clipboard|Wayland clipboard"
    "wl-clip-persist|Clipboard persistence"
    "cliphist|Clipboard history"
    "matugen|Material You color generator"
    "brightnessctl|Brightness control"
    "grim|Screenshot utility"
    "slurp|Region selection"
    "thunar|File manager"
    "polkit-kde-agent|Polkit agent"
    "xdg-desktop-portal-hyprland|XDG portal"
    "btop|System monitor"
    "fastfetch|System info"
    "nvtop|GPU monitor"
    "playerctl|Media control"
    "mpv|Video player"
    "imv|Image viewer"
    "ffmpeg|Media encoder"
    "wf-recorder|Screen recorder"
    "obs-studio|OBS Studio"
    "neovim|Text editor"
    "starship|Shell prompt"
    "yazi|Terminal file manager"
    "eza|Better ls"
    "bat|Better cat"
    "fd|Better find"
    "ripgrep|Better grep"
    "fzf|Fuzzy finder"
    "bluez|Bluetooth"
    "bluez-utils|Bluetooth utilities"
    "catppuccin-gtk-theme-mocha|Catppuccin GTK theme"
    "papirus-icon-theme|Papirus icons"
)

remove_hyprdots_configs() {
    log_section "Removing hyprdots configs"
    for d in hypr waybar rofi ghostty kitty swaync matugen; do
        if [[ -d "$HOME/.config/$d" ]]; then
            rm -rf "$HOME/.config/$d"
            log_ok "Removed: ~/.config/$d"
        fi
    done
    [[ -f "$HOME/.local/bin/wallset" ]] && rm -f "$HOME/.local/bin/wallset" && log_ok "Removed: wallset"
}

restore_from_backup() {
    log_section "Restoring Original Configs"
    while IFS= read -r entry; do
        [[ "$entry" == "__hyprland_preinstalled__" ]] && continue
        src="$BACKUP_DIR/$entry"
        dst="$HOME/.config/$entry"
        if [[ -d "$src" ]]; then
            rm -rf "$dst"
            cp -r "$src" "$dst"
            log_ok "Restored: ~/.config/$entry"
        else
            log_warn "Backup entry not found, skipping: $entry"
        fi
    done < "$MANIFEST"
    log_ok "Original configs restored"
}

generate_minimal_hyprland() {
    log_section "Generating Minimal Hyprland Config"
    mkdir -p "$HOME/.config/hypr"
    cat > "$HOME/.config/hypr/hyprland.conf" << 'MINIMAL'
# Minimal Hyprland config — generated by hyprdots uninstaller
monitor=,preferred,auto,1

$terminal = kitty
$menu     = wofi --show drun

exec-once = waybar

general {
    gaps_in     = 5
    gaps_out    = 10
    border_size = 2
    col.active_border   = rgba(cba6f7ff)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

decoration { rounding = 8 }
animations  { enabled = true }
dwindle     { preserve_split = true }

input {
    kb_layout    = us
    follow_mouse = 1
    sensitivity  = 0
}

$mainMod = SUPER

bind = $mainMod,       Q,     exec,          $terminal
bind = $mainMod,       SPACE, exec,          $menu
bind = $mainMod,       F4,    killactive,
bind = $mainMod,       M,     exit,
bind = $mainMod,       T,     togglefloating,
bind = $mainMod,       left,  movefocus,     l
bind = $mainMod,       right, movefocus,     r
bind = $mainMod,       up,    movefocus,     u
bind = $mainMod,       down,  movefocus,     d
bind = $mainMod,       1,     workspace,     1
bind = $mainMod,       2,     workspace,     2
bind = $mainMod,       3,     workspace,     3
bind = $mainMod,       4,     workspace,     4
bind = $mainMod,       5,     workspace,     5
bind = $mainMod SHIFT, 1,     movetoworkspace, 1
bind = $mainMod SHIFT, 2,     movetoworkspace, 2
bind = $mainMod SHIFT, 3,     movetoworkspace, 3
bind = $mainMod SHIFT, 4,     movetoworkspace, 4
bind = $mainMod SHIFT, 5,     movetoworkspace, 5
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
MINIMAL
    log_ok "Minimal hyprland.conf written — customize from here"
}

handle_packages() {
    log_section "Package Removal"
    log_warn "Only removes packages hyprdots installed — won't touch anything else"
    echo ""
    TO_REMOVE=()
    for entry in "${ALL_PACKAGES[@]}"; do
        pkg="${entry%%|*}"
        desc="${entry##*|}"
        if pacman -Qi "$pkg" &>/dev/null; then
            if ask "Remove $pkg ($desc)?"; then
                TO_REMOVE+=("$pkg")
            else
                log_info "Keeping: $pkg"
            fi
        fi
    done
    echo ""
    if [[ ${#TO_REMOVE[@]} -eq 0 ]]; then
        log_info "No packages selected for removal"
        return
    fi
    echo -e "${YELLOW}Packages to remove:${RESET}"
    for pkg in "${TO_REMOVE[@]}"; do echo "  - $pkg"; done
    echo ""
    if ask "Confirm removal of ${#TO_REMOVE[@]} packages?"; then
        paru -Rns --noconfirm "${TO_REMOVE[@]}"
        log_ok "Packages removed"
    else
        log_warn "Package removal cancelled"
    fi
}

main() {
    log_warn "This will remove hyprdots configs from your system"
    echo ""
    if ! ask "Are you sure you want to uninstall hyprdots?"; then
        log_info "Uninstall cancelled"
        exit 0
    fi

    remove_hyprdots_configs

    if [[ -f "$MANIFEST" ]] && [[ -s "$MANIFEST" ]]; then
        log_info "Backup found at $BACKUP_DIR"
        restore_from_backup
        rm -rf "$BACKUP_DIR"
        log_ok "Backup cleaned up"
    else
        log_warn "No backup found — generating minimal Hyprland config"
        generate_minimal_hyprland
    fi

    echo ""
    if ask "Do you want to review packages for removal?"; then
        handle_packages
    else
        log_info "Skipping package removal"
    fi

    echo ""
    log_ok "hyprdots uninstalled"
    echo ""
    if ask "Reboot now?"; then reboot
    else log_warn "Reboot or re-login for changes to take full effect"
    fi
}

main "$@"
