$red        = rgb(f7768e)
$redAlpha   = f7768e
$orange     = rgb(ff9e64)
$orangeAlpha = ff9e64
$yellow     = rgb(e0af68)
$yellowAlpha = e0af68
$green      = rgb(9ece6a)
$greenAlpha = 9ece6a
$teal       = rgb(73daca)
$tealAlpha  = 73daca
$blue       = rgb(7aa2f7)
$blueAlpha  = 7aa2f7
$cyan       = rgb(7dcfff)
$cyanAlpha  = 7dcfff
$purple     = rgb(bb9af7)
$purpleAlpha = bb9af7
$text       = rgb(c0caf5)
$textAlpha  = c0caf5
$subtext    = rgb(a9b1d6)
$subtextAlpha = a9b1d6
$surface2   = rgb(414868)
$surface2Alpha = 414868
$surface1   = rgb(283457)
$surface1Alpha = 283457
$surface0   = rgb(24283b)
$surface0Alpha = 24283b
$base       = rgb(1a1b26)
$baseAlpha  = 1a1b26
$mantle     = rgb(16161e)
$mantleAlpha = 16161e
