$red        = rgb(e06c75)
$redAlpha   = e06c75
$orange     = rgb(d19a66)
$orangeAlpha = d19a66
$yellow     = rgb(e5c07b)
$yellowAlpha = e5c07b
$green      = rgb(98c379)
$greenAlpha = 98c379
$cyan       = rgb(56b6c2)
$cyanAlpha  = 56b6c2
$blue       = rgb(61afef)
$blueAlpha  = 61afef
$purple     = rgb(c678dd)
$purpleAlpha = c678dd
$text       = rgb(abb2bf)
$textAlpha  = abb2bf
$subtext    = rgb(828997)
$subtextAlpha = 828997
$surface2   = rgb(4b5263)
$surface2Alpha = 4b5263
$surface1   = rgb(3e4451)
$surface1Alpha = 3e4451
$surface0   = rgb(2c313a)
$surface0Alpha = 2c313a
$base       = rgb(282c34)
$baseAlpha  = 282c34
$mantle     = rgb(21252b)
$mantleAlpha = 21252b
