accent=cba6f7
accent_rgb=rgb(cba6f7)
text=cdd6f4
subtext=bac2de
base=1e1e2e
mantle=181825
surface0=313244
surface1=45475a
surface2=585b70
red=f38ba8
green=a6e3a1
yellow=f9e2af
blue=89b4fa
purple=cba6f7
teal=94e2d5
name=Catppuccin Mocha
