accent=8839ef
accent_rgb=rgb(8839ef)
text=4c4f69
subtext=5c5f77
base=eff1f5
mantle=e6e9ef
surface0=ccd0da
surface1=bcc0cc
surface2=acb0be
red=d20f39
green=40a02b
yellow=df8e1d
blue=1e66f5
purple=8839ef
teal=179299
name=Catppuccin Latte
