$red        = rgb(cc241d)
$redAlpha   = cc241d
$orange     = rgb(d65d0e)
$orangeAlpha = d65d0e
$yellow     = rgb(d79921)
$yellowAlpha = d79921
$green      = rgb(98971a)
$greenAlpha = 98971a
$teal       = rgb(689d6a)
$tealAlpha  = 689d6a
$blue       = rgb(458588)
$blueAlpha  = 458588
$purple     = rgb(b16286)
$purpleAlpha = b16286
$text       = rgb(ebdbb2)
$textAlpha  = ebdbb2
$subtext    = rgb(d5c4a1)
$subtextAlpha = d5c4a1
$surface2   = rgb(665c54)
$surface2Alpha = 665c54
$surface1   = rgb(504945)
$surface1Alpha = 504945
$surface0   = rgb(3c3836)
$surface0Alpha = 3c3836
$base       = rgb(282828)
$baseAlpha  = 282828
$mantle     = rgb(1d2021)
$mantleAlpha = 1d2021
