# Fallback colors — overwritten by matugen when you run wallset
$primary              = rgb(adc7ff)
$onPrimary            = rgb(002e6a)
$primaryContainer     = rgb(004397)
$secondary            = rgb(bec6dc)
$tertiary             = rgb(dbbde1)
$background           = rgb(111318)
$surface              = rgb(111318)
$surfaceContainerHigh = rgb(272c33)
$onSurface            = rgb(e2e2e9)
$error                = rgb(ffb4ab)
