source = ~/.config/matugen/templates/hyprland-colors.conf

general {
    no_fade_in       = true
    no_fade_out      = true
    hide_cursor      = true
    grace            = 0
    disable_loading  = true
}

background {
    monitor      =
    path         = $HOME/Pictures/wallpaper/hypridle/back.jpg
    color        = $background
    blur_passes  = 0
    blur_size    = 0
    noise        = 0
    contrast     = 1
    brightness   = 1
}

label {
    monitor     =
    text        = $TIME
    color       = $primary
    font_size   = 80
    font_family = JetBrains Mono Nerd Font Bold
    position    = 0, 350
    halign      = center
    valign      = center
}

image {
    monitor      =
    path         = $HOME/Pictures/wallpaper/hypridle/profile.jpg
    size         = 120
    rounding     = -1
    border_size  = 4
    border_color = $primary
    position     = 0, 180
    halign       = center
    valign       = center
}

label {
    monitor     =
    text        = Hi there, $USER
    color       = $onSurface
    font_size   = 25
    font_family = JetBrains Mono Nerd Font
    position    = 0, 80
    halign      = center
    valign      = center
}

input-field {
    monitor           =
    size              = 280, 60
    outline_thickness = 2
    dots_size         = 0.2
    dots_spacing      = 0.2
    dots_center       = true
    outer_color       = $primary
    inner_color       = $surfaceContainerHigh
    font_color        = $onSurface
    fade_on_empty     = false
    placeholder_text  = Password...
    hide_input        = false
    check_color       = $secondary
    fail_color        = $error
    position          = 0, -20
    halign            = center
    valign            = center
}
