$red        = rgb(bf616a)
$redAlpha   = bf616a
$orange     = rgb(d08770)
$orangeAlpha = d08770
$yellow     = rgb(ebcb8b)
$yellowAlpha = ebcb8b
$green      = rgb(a3be8c)
$greenAlpha = a3be8c
$teal       = rgb(8fbcbb)
$tealAlpha  = 8fbcbb
$blue       = rgb(81a1c1)
$blueAlpha  = 81a1c1
$cyan       = rgb(88c0d0)
$cyanAlpha  = 88c0d0
$purple     = rgb(b48ead)
$purpleAlpha = b48ead
$text       = rgb(eceff4)
$textAlpha  = eceff4
$subtext    = rgb(d8dee9)
$subtextAlpha = d8dee9
$surface2   = rgb(4c566a)
$surface2Alpha = 4c566a
$surface1   = rgb(434c5e)
$surface1Alpha = 434c5e
$surface0   = rgb(3b4252)
$surface0Alpha = 3b4252
$base       = rgb(2e3440)
$baseAlpha  = 2e3440
$mantle     = rgb(242933)
$mantleAlpha = 242933
