accent=88c0d0
accent_rgb=rgb(88c0d0)
text=eceff4
subtext=d8dee9
base=2e3440
mantle=242933
surface0=3b4252
surface1=434c5e
surface2=4c566a
red=bf616a
green=a3be8c
yellow=ebcb8b
blue=81a1c1
purple=b48ead
teal=8fbcbb
name=Nord
