#!/bin/bash
# ── Phase 2: GPU Detection & Driver Setup ─────────────────────
source "$SCRIPT_DIR/scripts/lib.sh"

log_section "GPU Detection"

ENV_FILE="$SCRIPT_DIR/configs/hypr/env.conf"

detect_gpu() {
    local gpu_info
    gpu_info=$(lspci | grep -iE "vga|3d|display")

    HAS_NVIDIA=false
    HAS_AMD=false
    HAS_INTEL=false

    echo "$gpu_info" | grep -qi "nvidia" && HAS_NVIDIA=true
    echo "$gpu_info" | grep -qi "amd\|radeon\|advanced micro" && HAS_AMD=true
    echo "$gpu_info" | grep -qi "intel" && HAS_INTEL=true

    log_info "Detected GPU(s):"
    echo "$gpu_info" | while read -r line; do
        echo "         → $line"
    done
}

write_env() {
    cat > "$ENV_FILE" << ENVEOF
# ── Environment Variables — auto-generated by hyprdots installer ──
# ── GPU: $GPU_TYPE ──

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR,\$HOME/Pictures/Screenshots

$GPU_ENV_BLOCK
ENVEOF
    log_ok "GPU env vars written to env.conf"
}

detect_gpu

# ── NVIDIA only ───────────────────────────────────────────────
if $HAS_NVIDIA && ! $HAS_AMD && ! $HAS_INTEL; then
    GPU_TYPE="NVIDIA"
    log_info "NVIDIA GPU detected — installing drivers..."
    install_pkgs nvidia-dkms nvidia-utils nvidia-settings libva-nvidia-driver
    GPU_ENV_BLOCK=$(cat << 'NVENV'
# NVIDIA specific
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED,0
env = __GL_VRR_ALLOWED,0
NVENV
)
    log_ok "NVIDIA drivers installed"

# ── AMD only ──────────────────────────────────────────────────
elif $HAS_AMD && ! $HAS_NVIDIA; then
    GPU_TYPE="AMD"
    log_info "AMD GPU detected — installing drivers..."
    install_pkgs mesa vulkan-radeon libva-mesa-driver
    GPU_ENV_BLOCK=$(cat << 'AMDENV'
# AMD specific
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
AMDENV
)
    log_ok "AMD drivers installed"

# ── Intel only ────────────────────────────────────────────────
elif $HAS_INTEL && ! $HAS_NVIDIA && ! $HAS_AMD; then
    GPU_TYPE="Intel"
    log_info "Intel GPU detected — installing drivers..."
    install_pkgs mesa vulkan-intel intel-media-driver
    GPU_ENV_BLOCK=$(cat << 'INTENV'
# Intel specific
env = LIBVA_DRIVER_NAME,iHD
INTENV
)
    log_ok "Intel drivers installed"

# ── Hybrid: NVIDIA + Intel ────────────────────────────────────
elif $HAS_NVIDIA && $HAS_INTEL; then
    GPU_TYPE="Hybrid (Intel + NVIDIA)"
    log_warn "Hybrid GPU detected (Intel + NVIDIA)"
    log_info "Installing hybrid drivers..."
    install_pkgs mesa vulkan-intel intel-media-driver nvidia-dkms nvidia-utils libva-nvidia-driver
    GPU_ENV_BLOCK=$(cat << 'HYBENV'
# Hybrid Intel + NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
# Offload rendering to NVIDIA — comment these out if you want Intel primary
env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
HYBENV
)
    log_ok "Hybrid drivers installed"

# ── AMD + anything ────────────────────────────────────────────
else
    GPU_TYPE="Mixed/Unknown"
    log_warn "Could not confidently detect single GPU — using generic config"
    GPU_ENV_BLOCK="# Add your GPU env vars here manually"
fi

write_env
log_ok "GPU phase complete: $GPU_TYPE"
